apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-fruits-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: java-fruits-api
  template:
    metadata:
      labels:
        app: java-fruits-api
    spec:
      containers:
      - image: adambracey/java-fruits-api:8
        name: java-fruits-api
        ports:
        - containerPort: 8080
